language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI server's home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 파일 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * #before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springboot-webservice-tastemap.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings
    bucket: springboot-webservice-tastemap-build # S3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip파일 접근을 private로 설정
    local_dir: deploy # befor_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings
    bucket: springboot-webservice-tastemap-build # S3 bucket
    key: springboot-webservice-tastemap.zip
    bundle_type: zip
    application: springboot-webservice-tastemap
    deployment_group: springboot-webservice-tastemap
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - idforAnywhere@gmail.com